version: '3.8'
services:
  db:
    image: postgres:15
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo      
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo:
    image: odoo
    user: root
    depends_on:
      - db
    ports:
      - "10000:8069"
      - "20000:8072" # live chat
    tty: true
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    restart: always             # run as a service

volumes:
  odoo-db-data:
  odoo-data: